version: "3.9"

services:
  backend1:
    build:
      context: ./backend
    container_name: movie-backend-1
    expose:
      - "8080"

  backend2:
    build:
      context: ./backend
    container_name: movie-backend-2
    expose:
      - "8080"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"

  loadbalancer:
    image: haproxy:alpine
    container_name: haproxy
    ports:
      - "8080:80"  # Load balancer exposed on host: http://localhost:8080
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - backend1
      - backend2
